export ZSH="/home/egor/.oh-my-zsh"

# Plugins
plugins=(zsh-dircolors-nord)
plugins=(git)

# Theme
ZSH_THEME="lambda-minimal"

source $ZSH/oh-my-zsh.sh

# PATH to pip3
export PATH="${HOME}/.local/bin:$PATH"

# PATH to Rust
export PATH="$HOME/.cargo/bin:$PATH"

# PATH to i3 configs
export CONFIG="$HOME/.config/i3"

# PATH to `university` folder
export UNI="$HOME/Documents/university"

# Bluetooth start alias
alias bluetooth="sudo systemctl start bluetooth"

# Syntax
source $HOME/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Colorls
export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
export PATH="$PATH:$GEM_HOME/bin"
source $(dirname $(gem which colorls))/tab_complete.sh
alias ls='colorls'

# Python 3 alias
alias python="python3"

# Autocomplete
source $HOME/.config/zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh
zstyle ':autocomplete:*' min-delay .8

# Useful alias cd && ls
function cs() {
	cd "$@" && ls
}

alias cs="cs"
