#!/bin/bash

device="${BLOCK_INSTANCE:-wlp0s20f3}"
status=$(cat /sys/class/net/${device}/operstate)

URGENT_VALUE=20

if [[ "${status}" == "up" ]]; then
  if [[ -d "/sys/class/net/${device}/wireless" ]]; then
    quality=$(grep ${device} /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
	echo "${quality}% $(nmcli -t -f name connection show --active)"
    if [[ "${quality}" -le "${URGENT_VALUE}" ]]; then
		echo "OFF"
    fi
  else
    echo "ON"
  fi
else
  echo "OFF"
fi
