#!/bin/bash
BATTINFO=`acpi -b`
PERCENT=`cat /sys/class/power_supply/BAT0/capacity`
SAW=0
while true
do
    if [ $PERCENT -lt 10 ] && [ $SAW -eq 0 ] ; then
        notify-send -u critical "  Battery" "Need to charge laptop\n$BATTINFO"
        SAW=1
    else
        if [ $PERCENT -ge 10 ] ; then
            SAW=0
        fi
    fi
    sleep 1
done
