export ZSH="/home/egor/.oh-my-zsh"

# Plugins
plugins=(zsh-dircolors-nord)
plugins=(git)

# Theme
ZSH_THEME="lambda-minimal"

source $ZSH/oh-my-zsh.sh

# PATH to pip3
export PATH="${HOME}/.local/bin:$PATH"

# PATH to Rust
export PATH="$HOME/.cargo/bin:$PATH"

# PATH to Go
export PATH=$PATH:/usr/local/go/bin

# PATH to i3 configs
export CONFIG="$HOME/.config/i3"

# PATH to tmp folder
export TMP="$HOME/github/tmp"

# PATH to `university` folder
export UNI="$HOME/Documents/university"

# Syntax
source $HOME/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Colorls
export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
export PATH="$PATH:$GEM_HOME/bin"
source $(dirname $(gem which colorls))/tab_complete.sh
alias ls='colorls'

# Python 3 alias
alias python="python3"

# Autocomplete
source $HOME/.config/zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh
zstyle ':autocomplete:*' min-delay .8

# Open and kill tmux sessions
alias texit="tmux kill-server"

# Useful alias cd && ls
function cs() {
	cd "$@" && ls
}

alias cs="cs"
[ -f "/home/egor/.ghcup/env" ] && source "/home/egor/.ghcup/env" # ghcup-env

# Haskell
alias ghci="clear;ghci"

# Geckodriver
export PATH="$PATH:/usr/local/bin/geckodriver"

# QT settings
QT_DEVICE_PIXEL_RATIO=1
